### PR TITLE
Turn off CircleCI for commits

### PR DESCRIPTION
**Pull request by Hoverbear**
Post #867, this should remove the no longer required circleCI jobs.

### CODE REVIEW

**Review by pietroalbini — APPROVED** [review]
bors merge

**Comment by Hoverbear** [comment]
Hmmm

**Comment by Hoverbear** [comment]
Okay so based on several examples I've found `pr_status` needs to match the name of the `$job`, not the combined `$workflow / $job`.

**Review by pietroalbini — APPROVED** [review]
bors merge

**Pull request merged**
