### PR TITLE
[1.81] bump backtrace submodule to 0.3.74

### PR DESCRIPTION
**Pull request by japaric**
to fix the last qnx tests (backport of #859 ). this also bumps the libc subtree to 0.2.156 as the newer backtrace depends on that libc version

### CODE REVIEW

**Review by Hoverbear — APPROVED** [review]

**Comment by Hoverbear** [comment]
bors merge

**Comment by Hoverbear** [comment]
bors merge

**Comment by Hoverbear** [comment]
bors merge-

**Comment by Hoverbear** [comment]
That is a very odd windows failure

**Comment by Hoverbear** [comment]
I was able to confirm that this build failure happens locally on my windows machine as well.

**Comment by Veykril** [comment]
the standard library hooks the `windows_targets` crate itself, but notably it didn't have this at 1.81 yet, hence the failure. See current master having https://github.com/ferrocene/ferrocene/tree/main/library/windows_targets where as 1.81 lacks that. So you likely want to backport https://github.com/rust-lang/rust/pull/128873 as well

**Comment by japaric** [comment]
bors try

**Comment by japaric** [comment]
bors try

**Comment by Hoverbear** [comment]
bors merge

**Review by Hoverbear — APPROVED** [review]
bors merge

**Pull request merged**
