### PR TITLE
Allow building ferrocene docs on windows

### PR DESCRIPTION
**Pull request by Veykril**
Canonicalizing paths yields [extended length paths](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) on windows causing the paths to differ significantly if one of the two doesn't exist. From what I can tell we mainly want to get rid of any potential `..` and `.` segments from the paths though (and make them absolute), not resolve symlinks, so absolutizing should suffice.

Additionally this sets the encoding for text file `open` calls to `utf8` as that defaults to `cp1252` on windows.

### CODE REVIEW

**Comment by tshepang** [comment]
why the utf-8 encoding

**Comment by Veykril** [comment]
Was just editing the reason into the PR message, you were too fast for me :)

**Comment by tshepang** [comment]
is your normalize different from `Path::absolute` (introduced in 1.79)

**Comment by Veykril** [comment]
Oh, TIL about that function. Yes I think we should use that

**Review by tshepang — APPROVED** [review]
bors merge

**Pull request merged**
