### PR TITLE
Fix needs_proxy detection on Windows

### PR DESCRIPTION
**Pull request by Hoverbear**
I noticed that some of the manifests in the produced packages did not have `needs-proxy` set correctly. This should fix that.

### CODE REVIEW

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
No quite bors, the manifests still have false for some proxy-needers!

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try-

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try-

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try-

**Comment by Hoverbear** [comment]
Built!

```json
{
  "version": 1,
  "signatures": [
    {
      "key_sha256": "PYFFs4ioSd7PDyVUb93j7v97Rtg68JJBsM7yxGh6fU8=",
      "signature": "MEQCIG0wznW3MzEgcUUHsq19pGqblBdi7Y+o4Ez6DDVGOB8iAiAapDU5quud/Dh+gTERwoj1kCqOUdAaSLSxMzpg2wJR5w=="
    }
  ],
  "signed": "{\"product\":\"ferrocene\",\"package\":\"cargo-x86_64-pc-windows-msvc\",\"commit\":\"a16bd5f2f7d24a67ccb8f30683c70f691033881b\",\"files\":[{\"path\":\"bin\\\\cargo.exe\",\"posix-mode\":0,\"sha256\":\"cxbU3gU6kHoNGd7qhnRkvtqQLuvKp1nMaSYXkih7cBI=\",\"needs-proxy\":true},{\"path\":\"etc\\\\bash_completion.d\\\\cargo\",\"posix-mode\":0,\"sha256\":\"ML0Yn57jnRsJv5NUqtQ97fL4a4HNRxDclbIX9pPezDw=\",\"needs-proxy\":false},{\"path\":\"share\\\\doc\\\\cargo\\\\LICENSE-APACHE\",\"posix-mode\":0,\"sha256\":\"hGNYs6J7J+FDWfzXIJXmuuY7qBPvX/8BGUUBzuDTFx4=\",\"needs-proxy\":false},{\"path\":\"share\\\\doc\\\\cargo\\\\LICENSE-MIT\",\"posix-mode\":0,\"sha256\":\"NlFq79yExdWh50hUJZE6ItvaaesZMMXoTWrklytRlLk=\",\"needs-proxy\":false},{\"path\":\"share\\\\doc\\\\cargo\\\\LICENSE-THIRD-PARTY\",\"posix-mode\":0,\"sha256\":\"gYSKhBg0t9uuMzfQepHFLUmT08hck+QnCYRD8gEYBkE=\",\"needs-proxy\":false},{\"path\":\"share\\\\doc\\\\cargo\\\\README.md\",\"posix-mode\":0,\"sha256\":\"o77zy3Qx3N8GLJ4W5n+ifLmOocT6bbDXM5E34xGE8gw=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-add.1\",\"posix-mode\":0,\"sha256\":\"aNH9iGutdi9LI+hnobL/ULHWXHneEN2QLzkJcqeNnzo=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-bench.1\",\"posix-mode\":0,\"sha256\":\"AfUO6U4pRgqN+ErJICvujdkZTsAlGJYe/iFfNEPZH/I=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-build.1\",\"posix-mode\":0,\"sha256\":\"o3tf10bRWioh2awL2ZBc+cvTuEhQOsU/3Sj5lr0lEmY=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-check.1\",\"posix-mode\":0,\"sha256\":\"CoE/Z68zNXo8ufwI2Vk1xGmW00bBVuKE6chDP6TKSbE=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-clean.1\",\"posix-mode\":0,\"sha256\":\"4bcDNp7ZRSI3mIET3vIpSOAXI83qqRLstJ3rWTGGDOo=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-doc.1\",\"posix-mode\":0,\"sha256\":\"h3utA+jncAFWDoMAPTlyWOfK/CSW/K3iWuyhP46jN7M=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-fetch.1\",\"posix-mode\":0,\"sha256\":\"s2DybMH/8/oQbxkwpnZGT/0L2mNOLwHigKaNu7MxHv4=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-fix.1\",\"posix-mode\":0,\"sha256\":\"oD+c8//NyYeLlYSNaHIzRuDOdHn3Qsd+11eOYuii3ew=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-generate-lockfile.1\",\"posix-mode\":0,\"sha256\":\"sbRsVbpPxjGjBgF/DydnwQFwlu+UWWDUdyKhNo5TzWM=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-help.1\",\"posix-mode\":0,\"sha256\":\"MrLfrUGWSCUCiqUoA87n92QG+be5Y7rUFJDfQXzI/jA=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-init.1\",\"posix-mode\":0,\"sha256\":\"YCknLFK4yzk5TEY5S5lTYdVbcthfuTqQa4qRwJQNC0s=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-install.1\",\"posix-mode\":0,\"sha256\":\"N9SnFBkEa7FK5wC9mOmLW3u7hEa5rGzaNL/kOOJdhNY=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-locate-project.1\",\"posix-mode\":0,\"sha256\":\"AnKSBp3J7UUoPoWIHxZzucOa6TYyboqRfjQDSwOn6lI=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-login.1\",\"posix-mode\":0,\"sha256\":\"RxipYw6qyqjKUJ+jj0nRyOF7AABhr8DmJSTZcgNZKNM=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-logout.1\",\"posix-mode\":0,\"sha256\":\"Jqza6mOeopHWWWFM9nvM/K89kvXmSsgK6GyMLp+rEWI=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-metadata.1\",\"posix-mode\":0,\"sha256\":\"lTArA3Qi9iFi0s9zmt4xrkBFu/ESsACedxXIhAGIlMg=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-new.1\",\"posix-mode\":0,\"sha256\":\"6tWVXSB9xX/NRN9SdKGkvYrvy3pryGkrONfzFg2RJd4=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-owner.1\",\"posix-mode\":0,\"sha256\":\"//itQ3NMXe+xEXpjOlXnZ1flGHFSwgKNtGxV6hjOrUU=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-package.1\",\"posix-mode\":0,\"sha256\":\"aQh3rSD9I321w6wqXgdpY93jC9o2UN3TzRrjXTP5Tgw=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-pkgid.1\",\"posix-mode\":0,\"sha256\":\"55WXq4J71RwJr1GFem+c6HjdF8v28KO99TX4JloyRKs=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-publish.1\",\"posix-mode\":0,\"sha256\":\"gbawUMiIoTFJHfk5++APnRw34zottcKNTZG1NGnoCgs=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-remove.1\",\"posix-mode\":0,\"sha256\":\"eaCyQRK1xlx44FcP4PtbsGFbRhhVnpZJ50QeuJsSVjI=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-report.1\",\"posix-mode\":0,\"sha256\":\"FNCk5tQcnEAAC66PcFd0VnPEDFdOvZjPbkeE2siVtFc=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-run.1\",\"posix-mode\":0,\"sha256\":\"hfxPf6a0kZtA26j5p+ZrRul1LmNK3VEr4wGjRo/C6KQ=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-rustc.1\",\"posix-mode\":0,\"sha256\":\"2UfJavsucxxqCT/YVsRIuT2qwXp3GE8nnZZSpODkl34=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-rustdoc.1\",\"posix-mode\":0,\"sha256\":\"2qo4hrFfGzAt0enkltuzyQuejwQk9m80czFOJlxL7YQ=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-search.1\",\"posix-mode\":0,\"sha256\":\"9BgoShIWHK04lUx4x34y902OiMsoozUvevWfpHoEE9Y=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-test.1\",\"posix-mode\":0,\"sha256\":\"4vsy0r6UeOyX58yyaYazvYutzJA77VfFhKnPpXwCL10=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-tree.1\",\"posix-mode\":0,\"sha256\":\"t50NcSgkG3KMJxPqgm3gdNFUqb+xu1vwla1LNLuBJtY=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-uninstall.1\",\"posix-mode\":0,\"sha256\":\"6VdzwiokArbTF0aGpBhc+UmwFHtnXyDq1vNHXsNMsGU=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-update.1\",\"posix-mode\":0,\"sha256\":\"99GLiR78x+wYjVY6i7DQzH96neGjT2nKZ16N/VQtYLg=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-vendor.1\",\"posix-mode\":0,\"sha256\":\"RbQUn4X8PrHXOaJZWumh7f7tnxcTX34cInQryoAQTJU=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-verify-project.1\",\"posix-mode\":0,\"sha256\":\"pO8UByxq9lUEvxCOuHwoawKa/nD1UTdQ61ldAnJYajE=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-version.1\",\"posix-mode\":0,\"sha256\":\"KU8OkprHRqeY8LkwPIm9/VE7w0TH/T1eFVyjta9cNQg=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo-yank.1\",\"posix-mode\":0,\"sha256\":\"yD7bofJyd57v+otmuDHuvEw+k7I200J37cz4KEnwOyQ=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\cargo.1\",\"posix-mode\":0,\"sha256\":\"9R5+xQNSUYSpipMgIt+CUMIfgMUt33PD1nfDZ1jL86w=\",\"needs-proxy\":false},{\"path\":\"share\\\\zsh\\\\site-functions\\\\_cargo\",\"posix-mode\":0,\"sha256\":\"sF+eBQmdP04PwZdTNBiw8bk5wUxcf1Uu419/grkaeZM=\",\"needs-proxy\":false}],\"managed-prefixes\":[]}"
}
```

Note the `needs_proxy: true`

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
Here's an example of the produced JSON now:

```json
{
  "version": 1,
  "signatures": [
    {
      "key_sha256": "bku5PxjKdq19DreWbPnBMMQtWJpGMMZN4HmD1R9eG08=",
      "signature": "MEUCIQCfeGyITrQmXQToh8u+UAlXYyU/JZE1cqc8r6iBkRySywIgJsn8jxj0hRBxFhww6b+TU1roz3yqQofekjefMXAagok="
    }
  ],
  "signed": "{\"product\":\"ferrocene\",\"package\":\"rustc-x86_64-pc-windows-msvc\",\"commit\":\"26012a23e4f8f6ea1c5e5df99e81d1b94fdbc870\",\"files\":[{\"path\":\"bin\\\\rust-windbg.cmd\",\"posix-mode\":0,\"sha256\":\"QmB5kcjzBApee78iInIAfnQeqW6XSZoWvGqy/HerEPU=\",\"needs-proxy\":false},{\"path\":\"bin\\\\rustc.exe\",\"posix-mode\":0,\"sha256\":\"W2bbvWNn/EEPMm/mkeL49v41WEhwmLZyICvBEGxHeD8=\",\"needs-proxy\":true},{\"path\":\"bin\\\\rustc_driver-c4879d1842548694.dll\",\"posix-mode\":0,\"sha256\":\"6CXFCAcDpnWgbWX2p8RvD1SJfRS/qQuoaVHONazl0/Q=\",\"needs-proxy\":false},{\"path\":\"bin\\\\rustc_driver-c4879d1842548694.pdb\",\"posix-mode\":0,\"sha256\":\"IXEE25ivcLRd0wFS0npF15fRwXA5hKa4PZzClp4RMwI=\",\"needs-proxy\":false},{\"path\":\"bin\\\\rustc_main-65de3bd8dd9220f1.pdb\",\"posix-mode\":0,\"sha256\":\"w4WiJsR670eApBZkMZrYA+v/SQOLTsq54+ejciLQjno=\",\"needs-proxy\":false},{\"path\":\"bin\\\\rustdoc.exe\",\"posix-mode\":0,\"sha256\":\"9cgKL/5yUJOXMTQawcZgkWzHvDGkEd6Sh1zHRdCRBRY=\",\"needs-proxy\":true},{\"path\":\"bin\\\\std-7d6b6d706bc2fa50.dll\",\"posix-mode\":0,\"sha256\":\"ysV3pekvghnGaOJ7KdDDOl9p+0a/JW72yK4Qic8KqZA=\",\"needs-proxy\":false},{\"path\":\"bin\\\\std-7d6b6d706bc2fa50.pdb\",\"posix-mode\":0,\"sha256\":\"Pvh3gSs0ZX0mH9w776KOZyUpu/gzS/7Kw0z4GHITZG0=\",\"needs-proxy\":false},{\"path\":\"lib\\\\rustlib\\\\etc\\\\intrinsic.natvis\",\"posix-mode\":0,\"sha256\":\"rJl58CcuBqmkWtKF+ZGCQJ81yq+7wRowgMXIctiJOKQ=\",\"needs-proxy\":false},{\"path\":\"lib\\\\rustlib\\\\etc\\\\liballoc.natvis\",\"posix-mode\":0,\"sha256\":\"AFmqJc5zNaUDtP/0aDYFk8WBhYUGLRrgvJhDBBtZ2JA=\",\"needs-proxy\":false},{\"path\":\"lib\\\\rustlib\\\\etc\\\\libcore.natvis\",\"posix-mode\":0,\"sha256\":\"InIJz+2FZKCafXFM+/o3vWMFv8z5zVFBLze3SOfy+Qk=\",\"needs-proxy\":false},{\"path\":\"lib\\\\rustlib\\\\etc\\\\libstd.natvis\",\"posix-mode\":0,\"sha256\":\"2Jeu20Fkp6SYonlvCEZZHH/myLL8u3wKgZKBc1u6aSo=\",\"needs-proxy\":false},{\"path\":\"lib\\\\rustlib\\\\x86_64-pc-windows-msvc\\\\bin\\\\gcc-ld\\\\ld.lld.exe\",\"posix-mode\":0,\"sha256\":\"kwn8TEN5TmcUq/caPgX60aWy2CZYrXGbFqaROnDRWfU=\",\"needs-proxy\":false},{\"path\":\"lib\\\\rustlib\\\\x86_64-pc-windows-msvc\\\\bin\\\\gcc-ld\\\\ld64.lld.exe\",\"posix-mode\":0,\"sha256\":\"kwn8TEN5TmcUq/caPgX60aWy2CZYrXGbFqaROnDRWfU=\",\"needs-proxy\":false},{\"path\":\"lib\\\\rustlib\\\\x86_64-pc-windows-msvc\\\\bin\\\\gcc-ld\\\\lld-link.exe\",\"posix-mode\":0,\"sha256\":\"kwn8TEN5TmcUq/caPgX60aWy2CZYrXGbFqaROnDRWfU=\",\"needs-proxy\":false},{\"path\":\"lib\\\\rustlib\\\\x86_64-pc-windows-msvc\\\\bin\\\\gcc-ld\\\\wasm-ld.exe\",\"posix-mode\":0,\"sha256\":\"kwn8TEN5TmcUq/caPgX60aWy2CZYrXGbFqaROnDRWfU=\",\"needs-proxy\":false},{\"path\":\"lib\\\\rustlib\\\\x86_64-pc-windows-msvc\\\\bin\\\\rust-lld.exe\",\"posix-mode\":0,\"sha256\":\"CnLr1wkvLY9CJF5oN04HrZ0HtGQ+B07N66ZQSbgrOpY=\",\"needs-proxy\":false},{\"path\":\"share\\\\doc\\\\rust\\\\COPYRIGHT\",\"posix-mode\":0,\"sha256\":\"vQWB/vYis9iyWDbPcP634aemFx6p5EC0bf2nTEag7Q0=\",\"needs-proxy\":false},{\"path\":\"share\\\\doc\\\\rust\\\\LICENSE-APACHE\",\"posix-mode\":0,\"sha256\":\"Yseh419WQGiW16p8pS0MwNJyrAIrXSeW59aQXbijY2o=\",\"needs-proxy\":false},{\"path\":\"share\\\\doc\\\\rust\\\\LICENSE-MIT\",\"posix-mode\":0,\"sha256\":\"I/GOA9xJ35FiL+KnYXZJdATkbO2KcV2dK2enRGVxzKM=\",\"needs-proxy\":false},{\"path\":\"share\\\\doc\\\\rust\\\\README.md\",\"posix-mode\":0,\"sha256\":\"I++d82BDou0fa559G0A7d8nKf/NtLlOD58Njy+NDxe0=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\rustc.1\",\"posix-mode\":0,\"sha256\":\"LecyEkAoDHHrlQbcJOLD1aL+QEYoRo8oJBFR03n9j4g=\",\"needs-proxy\":false},{\"path\":\"share\\\\man\\\\man1\\\\rustdoc.1\",\"posix-mode\":0,\"sha256\":\"ElicfQU54p19FXEbOt8o730jRNBwU1epDuED5BgY73E=\",\"needs-proxy\":false}],\"managed-prefixes\":[]}"
}
```

Notice how `needs_proxy` now gets set for rustc.

**Review by pietroalbini — APPROVED** [review]
bors merge

**Pull request merged**
