### PR TITLE
update lockfiles during upstream-pull

### PR DESCRIPTION
**Pull request by tshepang**
This has some advantages
- avoids the manual work of approving mechanical PRs
- avoids using CI time for changes that can only rarely break a CI build
- avoids lockfiles and upstream pulls getting out of sync, which can result in confusion

### CODE REVIEW

**Review by Dajamante — APPROVED** [review]
bors merge

**Comment by pietroalbini** [comment]
This is also updating the lockfiles on beta and stable, while it should only do it on main.

**Comment by tshepang** [comment]
working on a PR

**Comment by tshepang** [comment]
> This is also updating the lockfiles on beta and stable, while it should only do it on main.

https://github.com/ferrocene/ferrocene/pull/613

**Pull request merged**
