### PR TITLE
Backport qnx tests to 24.11

### PR DESCRIPTION
**Pull request by Hoverbear**
We also need to backport https://github.com/ferrocene/ferrocene/pull/859 which depends on https://github.com/ferrocene/ferrocene/pull/854.

This backports 

#758 #811 #780 #787 #851 #852 #858 #860 #866

### CODE REVIEW

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try-

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try-

**Comment by Hoverbear** [comment]
bors try

**Review by japaric — APPROVED** [review]

**Comment by Hoverbear** [comment]
bors merge

**Pull request merged**
