### PR TITLE
[1.83] Unshallow on the beta channel

### PR DESCRIPTION
**Pull request by pvdrz**
backport of #1105

### CODE REVIEW

**Comment by Hoverbear** [comment]
I don't see the metadata in the commit. Please follow https://public-docs.ferrocene.dev/main/qualification/internal-procedures/backports.html#manual-backports so the metadata is added.

**Comment by tshepang** [comment]
https://github.com/ferrocene/ferrocene/pull/1115 would create a backport pr, which will result in a compatible commit

**Comment by pvdrz** [comment]
@Hoverbear I wasn't familiar with this. Thanks for pointing me to the docs.

**Comment by tshepang** [comment]
done with automation https://github.com/ferrocene/ferrocene/pull/1119

**Pull request closed without merging**
