### PR TITLE
Allow building all Sphinx docs at once, and error out if `--serve` is misused

### PR DESCRIPTION
**Pull request by pietroalbini**
This PR makes a few quality of life changes to the tooling used to build the documentation:

* There is now a new `./x doc ferrocene/doc`, which builds all the Sphinx documents at once. This is easier than manually listing all documents in the single `./x` invocation, and it's way faster than invoking `./x doc` multiple times[^1]. Bikeshedding welcome on the name, I'm not too happy about it (the only constraint is having the `ferrocene-` prefix).

* Passing `--serve` when multiple documents are requested will now print an error and exit. It was already unsupported to pass `--serve` with multiple documents, as it would only start the server for the first one, but it was a silent and unintuitive.

[^1]: When invoking `./x` to build any document, the build system first gathers the intersphinx artifacts from all the documents, and only then actually builds the requested document(s). Gathering the intersphinx artifacts takes a few seconds. If you build multiple documents in the same invocation, the intersphinx artifacts will be reused, but if you invoke `./x` multiple times they will be regenerated every single time.

### CODE REVIEW

**Review by Veykril — APPROVED** [review]
Some ideas: ` ferrocene-sphinx-complete`, `ferrocene-sphinx-full`, `ferrocene-docs-full`, `ferrocene-docs-complete`, `ferrocene-docs-all`

**Comment by amanjeev** [comment]
`ferrocene-docs-all` is my vote.

**Comment by pietroalbini** [comment]
Renamed to `ferrocene/doc` after internal discussion.

**Review by tshepang — APPROVED** [review]
bors merge

**Pull request merged**
