### PR TITLE
Update `libc`

### PR DESCRIPTION
**Pull request by pvdrz**
- **Remove temporary file that was added by accident**
- **chore: release (#3862)**
- **Fix "struct stat" on 32-bit FreeBSD 12+ (#3939)**
- **Escape backticks in changelog**
- **Fix dead references in patterns.rst**
- **Fix paragraph 7.2:16**
- **Add missing system-unwind abi string**

### CODE REVIEW

**Comment by Veykril** [comment]
Looks like a failed rebase

**Comment by Veykril** [comment]
You can pull only a single subtree by invoking `./ferrocene/tools/pull-subtrees/pull.py --target main --subtree libc`

**Review by amanjeev — APPROVED** [review]

**Comment by pvdrz** [comment]
bors merge

**Comment by pvdrz** [comment]
bors retry

**Pull request merged**
