### PR TITLE
run tests on aarch64 QNX

### PR DESCRIPTION
**Pull request by japaric**
this PR depends on #780 and includes its commits. only commits starting with "add script to prepare and run aarch64 QNX VM" belong to this PR

### CODE REVIEW

**Comment by japaric** [comment]
bors try

**Comment by japaric** [comment]
bors try-

**Comment by japaric** [comment]
bors try

**Comment by japaric** [comment]
bors try-

**Comment by japaric** [comment]
bors try

**Comment by japaric** [comment]
bors try-

**Comment by japaric** [comment]
bors try

**Comment by japaric** [comment]
bors try-

**Comment by japaric** [comment]
bors try

**Comment by japaric** [comment]
bors try-

**Comment by japaric** [comment]
bors try

**Review by Hoverbear — APPROVED** [review]
I am slighty worried about the fragility of the `sed` calls into the script, and would prefer we documented them. Otherwise, this looks good and a good evolution from #780 .

**Comment by Hoverbear** [comment]
bors try

**Review by Hoverbear — APPROVED** [review]
I'm a little bummed the test-runner scripts can't be somehow unified, but I understand why.

**Comment by japaric** [comment]
bors merge

**Review by Hoverbear — APPROVED** [review]
bors merge

**Comment by japaric** [comment]
bors retry

**Comment by japaric** [comment]
bors try

**Review by Hoverbear — APPROVED** [review]
bors merge

**Pull request merged**
