### PR TITLE
Use the new tarball naming scheme

### PR DESCRIPTION
**Pull request by pietroalbini**
This PR implements the new tarball naming scheme agreed in https://designs.ferrocene.dev/tarball-names.html. It also bumps the metadata version from 3 to 4, so that the release process can identify which naming scheme to use.

### CODE REVIEW

**Review by tshepang — APPROVED** [review]
bors merge

**Comment by pietroalbini** [comment]
bors cancel

Found a problem :sweat_smile:

**Comment by pietroalbini** [comment]
Changed the code that generates the metadata to use the build system's methods to retrieve the commit hash rather than shelling out to git. This is actually a behavior change, since the build system always generates a short hash 9 chars long (compared to the dynamic length returned by git).

This was needed because we are generating the commit hash in the tarball name using the build system's methods, and that would've resulted in the metadata not matching the tarballs we generate.

**Review by tshepang — APPROVED** [review]
bors merge

**Review by tshepang — APPROVED** [review]
bors merge

**Pull request merged**
