### PR TITLE
rustfmt has no qualification methods

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by Urhengulas** [comment]
Are you saying 11.4.6.2 only needs to be filled if we applied a qualification method? If so, then we should put "N/A" in all the subsections.

**Review by Urhengulas — CHANGES_REQUESTED** [review]
Are you saying 11.4.6.2 only needs to be filled if we applied a qualification method? If so, then we should put "N/A" in all the subsections.

**Comment by tshepang** [comment]
I think it's just 11.4.6.2f-h that needs to be omitted... the rest look applicable

**Review by Urhengulas — APPROVED** [review]
bors merge

**Pull request merged**
