### PR TITLE
Adjust things to meet uv changes (and version lock uv)

### PR DESCRIPTION
**Pull request by Hoverbear**
#1048 seems to be encountering some issues due to some recent changes to uv, this adjusts to meet those and also version locks us to prevent future issues.

### CODE REVIEW

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try-

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try-

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Review by tshepang — APPROVED** [review]
bors merge

**Pull request merged**
