### PR TITLE
Prepare `rustfmt` reports

### PR DESCRIPTION
**Pull request by Urhengulas**
Move `rustc` to dedicated subdirectory and adapt the links accordingly.

Note: In the `evaluation-report` I've split the `hazop` chapter into `hazops-words` and `hazop-nodes`. This is because the `hazop-words` are shared between tools, while the `hazop-nodes` are different for each tool.

### CODE REVIEW

**Review by pietroalbini — APPROVED** [review]
Looks good. As a followup, we should change all the IDs to have `RUSTC` in the name, as we'll also need to have `RUSTFMT` IDs.

**Comment by pietroalbini** [comment]
bors merge

**Comment by Urhengulas** [comment]
bors cancel

**Review by pietroalbini — APPROVED** [review]
bors merge

**Comment by Urhengulas** [comment]
bors cancel

**Review by pietroalbini — APPROVED** [review]
bors merge

**Review by pietroalbini — APPROVED** [review]
bors merge

**Pull request merged**
