### PR TITLE
Add `./x doc --fresh --debug-sphinx` flags

### PR DESCRIPTION
**Pull request by pietroalbini**
This PR adds two flags helpful when working on Sphinx extensions:

* `./x doc --fresh` ignores caches and does a fresh build of the document. I wanted to call the flag `--clean`, but that flag is already taken by bootstrap and rebuild everything including bootstrap itself.
* `./x doc --debug-sphinx` disables parallel building and shows tracebacks on exceptions.

It also documents the flags, plus `--serve` which wasn't documented before.

### CODE REVIEW

**Review by amanjeev — APPROVED** [review]
Thank you!

**Review by amanjeev — APPROVED** [review]

**Comment by pietroalbini** [comment]
bors merge

**Comment by pietroalbini** [comment]
Pushed a commit fixing the test and a commit fixing a bug I noticed while using the feature (details in the commit message).

**Comment by amanjeev** [comment]
Ah! the autocomplete only works for first level commands like `doc` and also it only works for `./x.py` and not for `./x` for me on fish. Anywho, looks ok!

**Review by amanjeev — APPROVED** [review]

**Comment by pietroalbini** [comment]
bors merge

**Pull request merged**
