### PR TITLE
fix segfaulting rustc when `download-ci-llvm = true`

### PR DESCRIPTION
**Pull request by japaric**
- the segfault occurred in the second / third C++ frame after `rustc` called into LLVM using the `PassWrapper.cpp` glue
- the segfault occurred due a ABI mismatch between those two frames
- both frames corresponded to LLVM C++ functions. (the first frame was the `PassWrapper.cpp` glue)
- one of the frames (functions) came from the LLVM library built in CI; the other frame was codegen'd locally
- when comparing to a rust-lang/rust build, it was found that both frames involved in the segfault were present in the LLVM library built in rust-lang/rust CI. the rust-lang/rust artifact did not result in a segfault
- the differences between the rust-lang/rust and ferrocene build settings are: (a) rust-lang/rust builds llvm as shared library; ferrocene builds them as static libraries. (b) rust-lang/rust uses `clang` and a newer version of `gcc` / `g++`
- building LLVM as shared libraries in ferrocene did not fix the segfault but additionally bumping the `gcc` / `g++` version (by way of using a newer base docker image) did

### CODE REVIEW

**Comment by japaric** [comment]
bors try

**Comment by japaric** [comment]
bors try

**Comment by japaric** [comment]
bors try

**Comment by japaric** [comment]
bors try

**Comment by japaric** [comment]
bors try

**Review by tshepang — APPROVED** [review]
bors merge

**Comment by tshepang** [comment]
we can get the directory (ubuntu-18) renamed (to ubuntu-20) in a future PR

**Comment by tshepang** [comment]
bors retry

**Comment by pietroalbini** [comment]
Superseded by https://github.com/ferrocene/ferrocene/pull/376.

**Pull request closed without merging**
