### PR TITLE
ci: temporarily disable qnx jobs

### PR DESCRIPTION
**Pull request by tshepang**

### CODE REVIEW

**Comment by tshepang** [comment]
bors try

**Comment by tshepang** [comment]
bors retry

**Comment by tshepang** [comment]
bors retry

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
bors merge

**Comment by tshepang** [comment]
bors retry

**Comment by tshepang** [comment]
failed with what looks like CI platform fault
> ferrocene/ci/scripts/upload-dist-artifacts.sh: line 22:  9603 Segmentation fault: 11  aws s3 cp --recursive "${DIST_DIR}/" "s3://${ARTIFACTS_BUCKET}/${ARTIFACTS_PREFIX}${CIRCLE_SHA1}/"

**Pull request merged**
