### PR TITLE
Add experimental armv8r-none-eabihf target

### PR DESCRIPTION
**Pull request by Hoverbear**
Adds an experimental `armv8r-none-eabihf` which is untested.

### CODE REVIEW

**Review by pietroalbini — APPROVED** [review]
bors merge

**Comment by pietroalbini** [comment]
You need to update [the docker image](https://github.com/ferrocene/ferrocene/blob/647bf588c2d608e16006d473ce2cee4ff513be1f/ferrocene/ci/docker-images/ubuntu-20/Dockerfile#L133-L136) to set the compiler for the target to `arm-none-eabi-gcc` / `arm-none-eabi-g++` (if present in the image, if not install them).

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
🎉

**Review by pietroalbini — APPROVED** [review]
bors merge

**Pull request merged**
