### PR TITLE
Add test results summary table

### PR DESCRIPTION
**Pull request by pietroalbini**
This PR adds a summary table in the "test results overview" page that lists how many tests were passed for each target, and links to the more detailed page.

image

### CODE REVIEW

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
bors merge

**Comment by pietroalbini** [comment]
bors try

**Comment by pietroalbini** [comment]
Cannot reproduce the failure locally, pushed a commit enabling stack traces in CI.

bors merge

**Comment by pietroalbini** [comment]
bors cancel

Wait wrong command.

bors try

**Comment by pietroalbini** [comment]
Rebased

**Review by Veykril — APPROVED** [review]

**Comment by Veykril** [comment]
bors merge

**Pull request merged**
