### PR TITLE
un-ignore test that has since been fixed

### PR DESCRIPTION
**Pull request by tshepang**
Fixed in https://github.com/ferrocene/ferrocene/pull/1046

### CODE REVIEW

**Comment by Dajamante** [comment]
Is this 131570?
I don't see the problem solved when I follow
https://github.com/rust-lang/rust/pull/131570
and
https://github.com/rust-lang/rust/issues/121058

**Comment by tshepang** [comment]
hm, that note is wrong then

**Comment by tshepang** [comment]
bors try

**Comment by tshepang** [comment]
@Dajamante tests passed for some reason

**Review by Dajamante — APPROVED** [review]
bors merge

**Comment by Dajamante** [comment]
I approved but I feel it's unsatisfactory to not be able to track to the actual fix upstream 😢 , when following 131570: [(ci) Update macOS Xcode to 15](https://www.github.com/rust-lang/rust/issues/131570)

**Pull request merged**
