### PR TITLE
Reusable cache.py

### PR DESCRIPTION
**Pull request by Hoverbear**
Builds on #758 and integrates with the llvm-cache.py to give us a single source for caching our `.tar.zst`s.

This also migrates `.circleci/calculate-parameters.py` to `ferrocene/ci/scripts/calculate_parameters.py` so as to:

1. Conform to python module naming conventions (we cannot import a `foo-bar`, but we can import a `foo_bar`)
2. Be able to import `llvm_cache.py` as a local module and call it, instead of using a CLI interface and facing weird venv issues.
  + We could, if we really wanted to, override `sys.path` and import it... But... that's gross.

### CODE REVIEW

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try-

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Review by pietroalbini — APPROVED** [review]

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
Noooo :(

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try-

**Comment by Hoverbear** [comment]
bors try

**Comment by Hoverbear** [comment]
bors try

**Review by pietroalbini — APPROVED** [review]
bors merge

**Pull request merged**
